services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    volumes:
      - ./pb_data:/pb_data
    ports:
      - "8090:8090"
    env_file:
          - .env